WebClient/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BusinessLogic.BindingModel;
using BusinessLogic.Interfaces;
using WebClient.Models;

namespace WebClient.Controllers
{
    public class AdminController : Controller
    {
        private string password = "qwerty";
        private readonly IClientLogic _client;

        public AdminController(IClientLogic client)
        {
            _client = client;
        }
        public IActionResult Index(AdminModel model)
        {
            if (model.Password == password)
            {
                Program.AdminMode = !Program.AdminMode;
                return RedirectToAction("Blocking");
            }
            else if (model.Password != password && model.Password != null)
            {
                ModelState.AddModelError("", "Вы ввели неверный пароль");
                return View();
            }
            return View();
        }
        public IActionResult Blocking()
        {
            ViewBag.Clients = _client.Read(null);
            return View();
        }
        public ActionResult Block(int id)
        {
            if (ModelState.IsValid)
            {
                var existClient = _client.Read(new ClientBindingModel
                {
                    Id = id
                }).FirstOrDefault();
                _client.CreateOrUpdate(new ClientBindingModel
                {
                    Id = id,
                    Email=existClient.Email,
                    Specialication = existClient.Specialication,
                    Login = existClient.Login,
                    Password = existClient.Password,
                    Block = !existClient.Block
                });
                return RedirectToAction("Blocking");
            }
            return RedirectToAction("Blocking");
        }
        public IActionResult Logout()
        {
            Program.AdminMode = false;
            return RedirectToAction("Index", "Home");
        }
    }
}

WebClient/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BusinessLogic.BindingModel;
using BusinessLogic.Interfaces;
using WebClient.Models;
using System.Text.RegularExpressions;

namespace WebClient.Controllers
{
    public class ClientController : Controller
    {
        private readonly IClientLogic _client;
        private readonly int passwordMinLength = 6;
        private readonly int passwordMaxLength = 20;
        private readonly int loginMinLength = 1;
        private readonly int loginMaxLength = 50;
        public ClientController(IClientLogic client)
        {
            _client = client;
        }
        public ActionResult Profile()
        {
            ViewBag.User = Program.Client;
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginModel client)
        {
            var clientView = _client.Read(new ClientBindingModel
            {
                Login = client.Login,
                Password = client.Password
            }).FirstOrDefault();
            if (clientView == null)
            {
                ModelState.AddModelError("", "Вы ввели неверный пароль, либо пользователь не найден");
                return View(client);
            }
            if (clientView.Block == true)
            {
                ModelState.AddModelError("", "Пользователь заблокирован");
                return View(client);
            }
            Program.Client = clientView;
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Logout()
        {
            Program.Client = null;
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Registration()
        {
            return View();
        }
        [HttpPost]
        public ViewResult Registration(RegistrationModel client)
        {
            if (String.IsNullOrEmpty(client.Login))
            {
                ModelState.AddModelError("", "Введите логин");
                return View(client);
            }
            if (client.Login.Length > loginMaxLength ||
           client.Login.Length < loginMinLength)
            {
                ModelState.AddModelError("", $"Длина логина должна быть от {loginMinLength} до {loginMaxLength} символов");
                return View(client);
            }
            var existClient =_client.ReadofRegistration(new ClientBindingModel
                {
                    Login = client.Login
                }).FirstOrDefault();
                if (existClient != null)
                {
                    ModelState.AddModelError("", "Данный логин уже занят");
                    return View(client);
                }
            if (String.IsNullOrEmpty(client.Email))
            {
                ModelState.AddModelError("", "Введите электронную почту");
                return View(client);
            }
            existClient = _client.ReadofRegistration(new ClientBindingModel
                {  
                    Email = client.Email
                }).FirstOrDefault();
                if (existClient != null)
                {
                    ModelState.AddModelError("", "Данный E-Mail уже занят");
                    return View(client);
                }
            if (!Regex.IsMatch(client.Email, @"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$"))
            {
                ModelState.AddModelError("", "Email введен некорректно");
                return View(client);
            }
            if (client.Password.Length > passwordMaxLength ||
            client.Password.Length < passwordMinLength)
            {
                ModelState.AddModelError("", $"Длина пароля должна быть от {passwordMinLength} до {passwordMaxLength} символов");
                return View(client);
            }
            if (String.IsNullOrEmpty(client.Specialication))
            {
                ModelState.AddModelError("", "Введите Specialication");
                return View(client);
            }
            if (String.IsNullOrEmpty(client.Password))
            {
                ModelState.AddModelError("", "Введите пароль");
                return View(client);
            }
                _client.CreateOrUpdate(new ClientBindingModel
                {
                    Specialication = client.Specialication,
                    Login = client.Login,
                    Password = client.Password,
                    Email = client.Email,
                    Block = false
                }) ;
                ModelState.AddModelError("", "Вы успешно зарегистрированы");
                return View("Registration", client);
            }
    }
}

WebClient/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BusinessLogic.Interfaces;


namespace WebClient.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseLogic _course;
        public CourseController(ICourseLogic course)
        {
            _course = course;
        }
        public IActionResult Course()
        {
            ViewBag.Courses = _course.Read(null);
            return View();
        }
    }
}

WebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Университет</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-info border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Университет</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        @if (Program.Client != null)
                        {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Profile">Личный кабинет</a>
                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Education" asp-action="Education">Образования</a>
                                    </li>
                                                    <li class="nav-item">
                                                        <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Course">Все Курсы</a>
                                                    </li>

                                                                    <li class="nav-item">
                                                                        <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Logout">Выйти</a>
                                                                    </li>}
                        @if (Program.AdminMode == true)
                        {
                                  <li class="nav-item">
                                           <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Blocking">Блокировка</a>
                                  </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Registration">Регистрация</a>
                                    </li>
                                    <li class="nav-item">
                                         <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Logout">Выйти</a>
                                    </li>}
                        @if (Program.Client == null && Program.AdminMode == false)
                        {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Login">Вход</a>
                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Режим администратора</a>
                                    </li>}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TravelAgencyWebClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>